services:
  - type: web
    name: webui
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVICE
        value: webui
      - key: LOGFIRE_TOKEN
        sync: false
      - key: TILING_SERVER
        value: "https://tiling.onrender.com"
      - key: OPENAI_API_KEY
        sync: false
      - key: CREATE_DATABASE
        value: "false"
      - key: PG_DSN
        fromDatabase:
          name: postgres
          property: connectionString
  - type: web
    name: tiling
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVICE
        value: tiling
      - key: LOGFIRE_TOKEN
        sync: false

databases:
  - name: postgres
    plan: starter
